/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.usandoguibuilder;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
/**
 *
 * @author gatopreto
 */
public class TelaJogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaJogo.class.getName());

    
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        PainelJogo.setBackground(new Color(100,100,100));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("JOGO - carcará vs cabrito");
        
        this.add(PainelJogo);
        this.setVisible(true);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelJogo = new javax.swing.JPanel();
        PosicaoSuperiorEsquerda = new com.mycompany.usandoguibuilder.PanelPaint();
        PosicaoSuperiorDireita = new com.mycompany.usandoguibuilder.PanelPaint();
        PosicaoCentral = new com.mycompany.usandoguibuilder.PanelPaint();
        PosicaoSuperiorCentral = new com.mycompany.usandoguibuilder.PanelPaint();
        PosicaoInferiorDireita = new com.mycompany.usandoguibuilder.PanelPaint();
        PosicaoInferiorEsquerda = new com.mycompany.usandoguibuilder.PanelPaint();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));

        PainelJogo.setBackground(new java.awt.Color(100, 100, 100));
        PainelJogo.setPreferredSize(new java.awt.Dimension(800, 600));

        PosicaoSuperiorEsquerda.setBackground(new java.awt.Color(100, 100, 100));
        PosicaoSuperiorEsquerda.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PosicaoSuperiorEsquerdaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        PosicaoSuperiorEsquerda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosicaoSuperiorEsquerdaMouseClicked(evt);
            }
        });

        PosicaoSuperiorDireita.setBackground(new java.awt.Color(100, 100, 100));
        PosicaoSuperiorDireita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosicaoSuperiorDireitaMouseClicked(evt);
            }
        });

        PosicaoCentral.setBackground(new java.awt.Color(100, 100, 100));
        PosicaoCentral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosicaoCentralMouseClicked(evt);
            }
        });

        PosicaoSuperiorCentral.setBackground(new java.awt.Color(100, 100, 100));
        PosicaoSuperiorCentral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosicaoSuperiorCentralMouseClicked(evt);
            }
        });

        PosicaoInferiorDireita.setBackground(new java.awt.Color(100, 100, 100));
        PosicaoInferiorDireita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosicaoInferiorDireitaMouseClicked(evt);
            }
        });
        PosicaoInferiorDireita.setLayout(new java.awt.GridLayout(1, 0));

        PosicaoInferiorEsquerda.setBackground(new java.awt.Color(100, 100, 100));
        PosicaoInferiorEsquerda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosicaoInferiorEsquerdaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelJogoLayout = new javax.swing.GroupLayout(PainelJogo);
        PainelJogo.setLayout(PainelJogoLayout);
        PainelJogoLayout.setHorizontalGroup(
            PainelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelJogoLayout.createSequentialGroup()
                .addGroup(PainelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelJogoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(PosicaoSuperiorEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)
                        .addComponent(PosicaoSuperiorDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelJogoLayout.createSequentialGroup()
                        .addGroup(PainelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelJogoLayout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addGroup(PainelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PosicaoSuperiorCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PosicaoCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelJogoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PosicaoInferiorEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)))
                        .addComponent(PosicaoInferiorDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        PainelJogoLayout.setVerticalGroup(
            PainelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelJogoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(PosicaoSuperiorCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(PosicaoCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelJogoLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(PainelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PosicaoSuperiorDireita, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(PosicaoSuperiorEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(PainelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PosicaoInferiorEsquerda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PosicaoInferiorDireita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PosicaoCentralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicaoCentralMouseClicked
       
       int eixoX = evt.getX();
        int eixoY = evt.getY();
        
        Cabrito novoCabrito = new Cabrito();
        
        if(PosicaoCentral.clicouNoCirculo(eixoX, eixoY)){
            
            PosicaoCentral.add(novoCabrito);
            PosicaoCentral.revalidate();
            PosicaoCentral.repaint();
        } 
    }//GEN-LAST:event_PosicaoCentralMouseClicked
    //click no botão inferior
    private void PosicaoInferiorDireitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicaoInferiorDireitaMouseClicked
        int eixoX = evt.getX();
        int eixoY = evt.getY();
        
        Cabrito novoCabrito = new Cabrito();
        
        if(PosicaoInferiorDireita.clicouNoCirculo(eixoX, eixoY)){
            
            PosicaoInferiorDireita.add(novoCabrito);
            PosicaoInferiorDireita.revalidate();
            PosicaoInferiorDireita.repaint();
        }
        
    }//GEN-LAST:event_PosicaoInferiorDireitaMouseClicked

    private void PosicaoSuperiorCentralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicaoSuperiorCentralMouseClicked
        int eixoX = evt.getX();
        int eixoY = evt.getY();
        
        Cabrito novoCabrito = new Cabrito();
        
        if(PosicaoSuperiorCentral.clicouNoCirculo(eixoX, eixoY)){
            PosicaoSuperiorCentral.add(novoCabrito);
            PosicaoSuperiorCentral.revalidate();
            PosicaoSuperiorCentral.repaint();
        }
        
        
    }//GEN-LAST:event_PosicaoSuperiorCentralMouseClicked

    private void PosicaoInferiorEsquerdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicaoInferiorEsquerdaMouseClicked
        int eixoX = evt.getX();
        int eixoY = evt.getY();

        Cabrito novoCabrito = new Cabrito();

        if(PosicaoInferiorEsquerda.clicouNoCirculo(eixoX, eixoY)){

            PosicaoInferiorEsquerda.add(novoCabrito);
            PosicaoInferiorEsquerda.revalidate();
            PosicaoInferiorEsquerda.repaint();
        }
    }//GEN-LAST:event_PosicaoInferiorEsquerdaMouseClicked

    private void PosicaoSuperiorDireitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicaoSuperiorDireitaMouseClicked
        int eixoX = evt.getX();
        int eixoY = evt.getY();

        Cabrito novoCabrito = new Cabrito();

        if(PosicaoSuperiorDireita.clicouNoCirculo(eixoX, eixoY)){

            PosicaoSuperiorDireita.add(novoCabrito);
            PosicaoSuperiorDireita.revalidate();
            PosicaoSuperiorDireita.repaint();
        }
    }//GEN-LAST:event_PosicaoSuperiorDireitaMouseClicked

    private void PosicaoSuperiorEsquerdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicaoSuperiorEsquerdaMouseClicked
        int eixoX = evt.getX();
        int eixoY = evt.getY();

        Cabrito novoCabrito = new Cabrito();

        if(PosicaoSuperiorEsquerda.clicouNoCirculo(eixoX, eixoY)){

            PosicaoSuperiorEsquerda.add(novoCabrito);
            PosicaoSuperiorEsquerda.revalidate();
            PosicaoSuperiorEsquerda.repaint();
        }
    }//GEN-LAST:event_PosicaoSuperiorEsquerdaMouseClicked

    private void PosicaoSuperiorEsquerdaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PosicaoSuperiorEsquerdaAncestorAdded
        Cabrito novoCabrito = new Cabrito();
        if(novoCabrito.isAncestorOf(PosicaoSuperiorEsquerda)){
            System.out.println("é ancestral");
        }
    }//GEN-LAST:event_PosicaoSuperiorEsquerdaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaJogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelJogo;
    private com.mycompany.usandoguibuilder.PanelPaint PosicaoCentral;
    private com.mycompany.usandoguibuilder.PanelPaint PosicaoInferiorDireita;
    private com.mycompany.usandoguibuilder.PanelPaint PosicaoInferiorEsquerda;
    private com.mycompany.usandoguibuilder.PanelPaint PosicaoSuperiorCentral;
    private com.mycompany.usandoguibuilder.PanelPaint PosicaoSuperiorDireita;
    private com.mycompany.usandoguibuilder.PanelPaint PosicaoSuperiorEsquerda;
    // End of variables declaration//GEN-END:variables
}
